version: 2.1
jobs:
  rubocop:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          RAILS_ENV: test

      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_HOST: '127.0.0.1'
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: root

    working_directory: ~/quest_review

    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gemfiles-{{ .Branch }}-
            - gemfiles-master-

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      # Store bundle cache
      - save_cache:
          key: gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Rubocop
      - run:
          name: Rubocop
          command: bundle exec rubocop

  rspec:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          RAILS_ENV: test

      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_HOST: '127.0.0.1'
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: root

    working_directory: ~/quest_review

    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gemfiles-{{ .Branch }}-
            - gemfiles-master-

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      # Store bundle cache
      - save_cache:
          key: gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # DB setup
      - run: mv ./config/database.yml.ci ./config/database.yml

      # DB setup
      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load

      # Chrome-driver setup
      - run:
          name: Update ChromeDriver Version
          command: |
            CHROME_VERSION=$(google-chrome --version | sed -r 's/[^0-9]+([0-9]+\.[0-9]+\.[0-9]+).*/\1/g')
            CHROMEDRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
            bundle exec chromedriver-update $CHROMEDRIVER_VERSION

      # Rspec
      - run:
          name: Rspec
          command: bundle exec rspec

workflows:
  version: 2.1
  build:
    jobs:
      - rubocop
      - rspec

